repos:
-   repo: https://github.com/novasamatech/pre-commit-hooks
    rev: c1b66a8fa80dfc7e21aa3c0261fbe190fe68970b
    hooks:
    -   id: check-chains-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
