repos:
-   repo: https://github.com/novasamatech/pre-commit-hooks
    rev: a0eca3e206a0ee7d824489540565ce280c1d2da9
    hooks:
    -   id: check-chains-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
