repos:
-   repo: https://github.com/stepanLav/pre-commit-hooks
    rev: e89ab43b0c47945cd70e9f81f8f1cd4245e0060f
    hooks:
    -   id: check-chains-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
