repos:
-   repo: https://github.com/novasamatech/pre-commit-hooks
    rev: cd059677152a3607695b45d77abb40923f4cf392
    hooks:
    -   id: check-chains-json
    -   id: check-dapps-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
