repos:
-   repo: https://github.com/novasamatech/pre-commit-hooks
    rev: 47035233ee297f7dda321e78df1dcd41929dc1dc
    hooks:
    -   id: check-chains-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
