repos:
-   repo: https://github.com/novasamatech/pre-commit-hooks
    rev: 60a603fc64cc2c80423aa10504b63cbe630db744
    hooks:
    -   id: check-chains-json
    -   id: check-dapps-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
