repos:
-   repo: https://github.com/novasamatech/pre-commit-hooks
    rev: 8a757bbc1f7b6faad1cb06968641a2fdf5d2b36b
    hooks:
    -   id: check-chains-json
    -   id: check-dapps-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
