repos:
-   repo: https://github.com/novasamatech/pre-commit-hooks
    rev: b62fde7528ee4a906985693d4a46fab9693e56d4
    hooks:
    -   id: check-chains-json
    -   id: check-dapps-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
