name: Check nodes availability

on:
  workflow_dispatch:
  pull_request:

env:
  JSON_PATH: "/chains/v4/chains.json"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        tests:
          [
            ./tests/test_nodes_availability.py,
            ./tests/test_network_parameters.py,
            ./tests/test_can_query_base_parameters.py,
            ./tests/test_xcm_data.py,
          ]
    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v1

      - name: Set up actual paths
        uses: ./.github/workflows/setup-path

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run test
        run: python -m pytest --rootdir . --alluredir=allure-report/ -n auto "${{ matrix.tests }}" --reruns 5 --reruns-delay 5

      - name: Tar files
        if: always()
        run: tar -cvf allure-report.tar ./allure-report/

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure
          path: ./allure-report.tar

  make-report:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - uses: actions/checkout@v2
      - name: Download built artifact
        uses: actions/download-artifact@v2
        with:
          name: allure
          path: ./nova-utils

      - name: Unzip results
        run: |
          cd ./nova-utils
          tar -xvf allure-report.tar

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          repository: nova-wallet/testrunner
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug
        run: |
          ls -R

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-report
          allure_history: allure-history
          keep_reports: 30

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PAT_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
